/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesVetPet;


public class InterfazPacientes extends javax.swing.JFrame {
            
    public InterfazPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnGestionarPaciente = new javax.swing.JButton();
        btnGestionarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(639, 468));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡¡Bienvenido!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 130, 30));

        btnCerrar.setBackground(new java.awt.Color(0, 153, 153));
        btnCerrar.setFont(new java.awt.Font("LEMON MILK", 1, 10)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(204, 0, 0));
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 50, -1));

        btnRegistrar.setBackground(new java.awt.Color(0, 204, 102));
        btnRegistrar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar Paciente");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, 40));

        btnGestionarPaciente.setBackground(new java.awt.Color(0, 204, 102));
        btnGestionarPaciente.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnGestionarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPaciente.setText("Gestionar Paciente");
        btnGestionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 170, 40));

        btnGestionarCita.setBackground(new java.awt.Color(0, 204, 102));
        btnGestionarCita.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnGestionarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarCita.setText("Gestionar Cita");
        btnGestionarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        RegistrarPaciente a = new RegistrarPaciente();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGestionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPacienteActionPerformed
        GestionaPaciente b = new GestionaPaciente();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionarPacienteActionPerformed

    private void btnGestionarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCitaActionPerformed
        GestionarCita c = new GestionarCita();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestionarCitaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGestionarCita;
    private javax.swing.JButton btnGestionarPaciente;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
