/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesVetPet;

import GestionVetPet.Paciente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

public class RegistrarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPaciente
     */
    public RegistrarPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        textAreaRegistro.setEditable(false);
    }
    
    private void mostrarPacientesEnTextArea(ArrayList<Paciente> pacientes) {
    // Limpiar el JTextArea antes de mostrar nuevos registros
    textAreaRegistro.setText("");

    // Mostrar cada paciente en el JTextArea
    for (Paciente paciente : pacientes) {
        // Formatear la información detallada del paciente
        String pacienteFormateado = String.format(
                "Nombre del Paciente: %s\n" +
                "Nombre del Dueño: %s\n" +
                "Edad: %d\n" +
                "Categoría: %s\n" +
                "Raza: %s\n" +
                "Sexo: %s\n" +
                "Fecha de Inscripción: %s\n" +
                "Altura: %.2f\n" +
                "Peso: %.2f\n" +
                "ID Único: %d\n" +
                "Pelaje: %s\n" +
                "Fecha de Nacimiento: %s\n\n",
                paciente.getNombre(), paciente.getNombreDueño(), paciente.getEdad(),
                paciente.getCategoria(), paciente.getRaza(), paciente.getSexo(),
                paciente.getFechaInscripcion(), paciente.getAltura(), paciente.getPeso(),
                paciente.getIdUnico(), paciente.getPelaje(), paciente.getFechaNacimiento()
        );

        // Agregar la información del paciente al JTextArea
        textAreaRegistro.append(pacienteFormateado);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        textAreaRegistro = new java.awt.TextArea();
        texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt1 = new javax.swing.JTextField();
        Txt2 = new javax.swing.JTextField();
        Txt3 = new javax.swing.JTextField();
        Txt4 = new javax.swing.JTextField();
        Txt5 = new javax.swing.JTextField();
        Txt6 = new javax.swing.JTextField();
        Txt7 = new javax.swing.JTextField();
        Txt8 = new javax.swing.JTextField();
        Txt9 = new javax.swing.JTextField();
        Txt10 = new javax.swing.JTextField();
        Txt11 = new javax.swing.JTextField();
        Txt12 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();
        btnVerPacientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 0, -1, -1));

        textAreaRegistro.setVisible(false);
        getContentPane().add(textAreaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 430, 530));

        texto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        texto.setText("¡¡BIENVENIDO!!");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 36, -1, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 75, -1, -1));

        jLabel2.setText("Nombre del Dueño:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 122, -1, -1));

        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 167, -1, -1));

        jLabel4.setText("Categoría:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 215, -1, -1));

        jLabel5.setText("Raza:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 263, -1, -1));

        jLabel6.setText("Sexo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 311, -1, -1));

        jLabel7.setText("Fecha de Inscripción:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 362, -1, -1));

        jLabel8.setText("Altura:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 407, -1, -1));

        jLabel9.setText("Peso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 449, -1, -1));

        jLabel10.setText("Id Unico:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 492, -1, -1));

        jLabel11.setText("Pelaje:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 539, -1, -1));

        jLabel12.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 583, -1, -1));

        Txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 73, 274, -1));

        Txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 120, 274, -1));
        getContentPane().add(Txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 165, 274, -1));
        getContentPane().add(Txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 213, 274, -1));
        getContentPane().add(Txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 261, 274, -1));

        Txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt6ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 309, 274, -1));
        getContentPane().add(Txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 360, 274, -1));
        getContentPane().add(Txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 405, 274, -1));
        getContentPane().add(Txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 447, 274, -1));
        getContentPane().add(Txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 490, 274, -1));
        getContentPane().add(Txt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 537, 274, -1));

        Txt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt12ActionPerformed(evt);
            }
        });
        getContentPane().add(Txt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 581, 274, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 632, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 632, -1, -1));

        btnEliminarPaciente.setText("Eliminar Paciente");
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 685, -1, -1));

        btnVerPacientes.setText("Ver Registro");
        btnVerPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 632, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void Txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2ActionPerformed

    private void Txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt6ActionPerformed

    private void Txt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt12ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        InterfazPacientes a = new InterfazPacientes();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void Txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
        // Obtener los valores de los JTextField
    String nombre = Txt1.getText();
    String nombreDueño = Txt2.getText();
    int edad = Integer.parseInt(Txt3.getText());
    String categoria = Txt4.getText();
    String raza = Txt5.getText();
    String sexo = Txt6.getText();
    Date fechaInscripcion = obtenerFechaDesdeTextField(Txt7);
    double altura = Double.parseDouble(Txt8.getText());
    double peso = Double.parseDouble(Txt9.getText());
    int idUnico = Integer.parseInt(Txt10.getText());
    String pelaje = Txt11.getText();
    Date fechaNacimiento = obtenerFechaDesdeTextField(Txt12);

    // Crear un nuevo objeto Paciente con los datos ingresados
    Paciente nuevoPaciente = new Paciente(nombre, nombreDueño, edad, categoria, raza, sexo,
            fechaInscripcion, altura, peso, idUnico, pelaje, fechaNacimiento);

    // Guardar el nuevo paciente en el archivo
    nuevoPaciente.guardarPacienteEnArchivo();
    
    // Limpiar los campos después de guardar
    Txt1.setText("");
    Txt2.setText("");
    Txt3.setText("");
    Txt4.setText("");
    Txt5.setText("");
    Txt6.setText("");
    Txt7.setText("");
    Txt8.setText("");
    Txt9.setText("");
    Txt10.setText("");
    Txt11.setText("");
    Txt12.setText("");
}

private Date obtenerFechaDesdeTextField(javax.swing.JTextField textField) {
    try {
        return new SimpleDateFormat("yyyy-MM-dd").parse(textField.getText());
    } catch (ParseException e) {
        e.printStackTrace();
        return null;
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPacientesActionPerformed
        // Cargar los pacientes desde el archivo
    ArrayList<Paciente> pacientes = Paciente.cargarPacientesDesdeArchivo();

    // Mostrar los pacientes en el JTextArea
    mostrarPacientesEnTextArea(pacientes);

    // Mostrar el JTextArea
    textAreaRegistro.setVisible(true);
    }//GEN-LAST:event_btnVerPacientesActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        // Pedir al usuario que ingrese el ID único a eliminar
    String input = JOptionPane.showInputDialog(this, "Ingrese el ID único del paciente a eliminar:");

    if (input != null && !input.isEmpty()) {
        try {
            int idUnicoEliminar = Integer.parseInt(input);

            // Cargar los pacientes desde el archivo
            ArrayList<Paciente> pacientes = Paciente.cargarPacientesDesdeArchivo();

            // Eliminar el paciente por su ID único
            Paciente.eliminarPacientePorId(pacientes, idUnicoEliminar);

            // Actualizar el archivo con la nueva lista de pacientes
            Paciente.guardarPacientesEnArchivo(pacientes);

            // Mostrar los pacientes actualizados en el JTextArea
            mostrarPacientesEnTextArea(pacientes);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para el ID único.");
        }
    }
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt1;
    private javax.swing.JTextField Txt10;
    private javax.swing.JTextField Txt11;
    private javax.swing.JTextField Txt12;
    private javax.swing.JTextField Txt2;
    private javax.swing.JTextField Txt3;
    private javax.swing.JTextField Txt4;
    private javax.swing.JTextField Txt5;
    private javax.swing.JTextField Txt6;
    private javax.swing.JTextField Txt7;
    private javax.swing.JTextField Txt8;
    private javax.swing.JTextField Txt9;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerPacientes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextArea textAreaRegistro;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
